"""
The honest test. Replays a set of (label, price-path) records through the SAME
deterministic strategy the live bot uses, fills them through the SimBroker with
a slippage haircut, and scores the result against a buy-and-hold benchmark.

Because labels are cached (not regenerated by the LLM each run), this is fully
deterministic and free to run a thousand times while you tune thresholds.

Input format (data/labels.jsonl), one JSON object per line:
{
  "label": {"tickers":["TSLA"],"sentiment":0.7,"confidence":0.8,"event_type":"earnings"},
  "entry_price": 250.0,
  "exit_price": 256.0          // price when the bracket/horizon resolved
}

The included sample (data/sample_labels.jsonl) is SYNTHETIC -- it exists to prove
the pipeline runs, NOT to suggest the strategy works. Replace it with real
archived news+prices before you trust a single number.
"""
from __future__ import annotations

import json
import sys

from . import config
from .labels import Label
from .strategy import decide
from .simbroker import SimBroker
from . import metrics


def load_records(path: str) -> list[dict]:
    records = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if line:
                records.append(json.loads(line))
    return records


def run(path: str, benchmark_return: float = 0.0) -> dict:
    cfg = config.load()
    broker = SimBroker(cfg.sim)
    open_syms: set[str] = set()

    for rec in load_records(path):
        ld = rec["label"]
        label = Label(
            tickers=[t.upper() for t in ld.get("tickers", [])],
            sentiment=float(ld.get("sentiment", 0.0)),
            confidence=float(ld.get("confidence", 0.0)),
            event_type=ld.get("event_type", "unknown"),
        )
        intent = decide(label, cfg.strategy, open_syms)
        if intent is None:
            continue
        side = "long" if intent.side == "buy" else "short"
        broker.open(intent.symbol, intent.notional, rec["entry_price"], side)
        broker.close(intent.symbol, rec["exit_price"])

    stats = metrics.summarize(broker.closed, broker.equity_curve, benchmark_return)
    return stats


if __name__ == "__main__":
    path = sys.argv[1] if len(sys.argv) > 1 else "data/sample_labels.jsonl"
    bench = float(sys.argv[2]) if len(sys.argv) > 2 else 0.0
    stats = run(path, bench)
    print(metrics.format_report(stats))
